version: '3.9'
services:
  cron:
    image: nalewczy/magento2-cron-amd64
    depends_on:
      - apache
      - varnish
    links:
      - db
      - cache
      - sessions
      - clusterdata
      - apache
      - varnish
      - elasticsearch
    volumes:
      - html_data:/var/www/html
      - type: bind
        source: ./varnish.secret
        target: /varnish.secret
        consistency: consistent

  ssl:
    image: nalewczy/nginx-ssl-for-magento2-amd64
    depends_on:
      - varnish
    links:
      - varnish
    ports:
      - "443:443"

  varnish:
    image: varnish:7.1
    ports:
      - "80:80"
      - "6082:6082"
    depends_on:
      - apache
    links:
      - apache
    volumes:
      - ./varnish.vcl:/etc/varnish/default.vcl
      - ./varnish.secret:/etc/varnish/secret
    environment:
      - CACHE_SIZE=256M

  apache:
    image: nalewczy/magento2-apache-php-amd64
    environment:
      - MAGENTO_REPO
      - API_KEY
      - API_SECRET
      - MAGENTO_VERSION
      - TIMEZONE
      - CURRENCY
      - ADMIN_EMAIL
      - ADMIN_PASSWORD
    depends_on:
      - db
      - cache
      - clusterdata
    links:
      - db
      - cache
      - sessions
      - clusterdata
    volumes:
      - html_data:/var/www/html

  db:
    image: mysql:8.0
    container_name: docker-magento2_db_1
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/mysql
        consistency: delegated
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
      - MYSQL_LOG_BIN_TRUST_FUNCTION_CREATORS=1

  elasticsearch:
    image: elasticsearch:7.17.17
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    ports:
      - "9300:9300"
      - "9200:9200"

  cache:
    image: nalewczy/redis-volatile-amd64

  clusterdata:
    image: nalewczy/redis-volatile-amd64

  sessions:
    image: redis:6.2

volumes:
  dbdata:
  html_data:
